[package]
name = "bevy_wasm_mouse_move"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.4.0"
bevy = { version = "0.5", default-features = false, features = ["bevy_winit", "render"] }
wasm-bindgen = "0.2"
web-sys = "0.3.4"
